properties:
    - key: 'server.apppath'
      value : '/workflow-repository/api/v1'
    - key: server.url
      value : 'http://localhost'
    - key: 'server.port'
      value: 5000
    - key: 'app.doc'
      value: 'http://cds-swg1.cims.nyu.edu/workflow-repository/api/v1/doc/index.html'
    - key: 'db.uri'
      value:
          type: 'YAML'
          properties:
              resourceUri: 'https://raw.githubusercontent.com/heikomuller/yadage-workflow-repository/master/config/yadage-workflows.yaml'
    - key: 'db.schema'
      value:
          type: 'JSON'
          properties:
              resourceUri: 'https://raw.githubusercontent.com/diana-hep/yadage-schemas/master/yadageschemas/yadage/workflow-schema.json'
