templates:
    - identifier: 'lhcoanalysis'
      name: 'LHC Analysis'
      description: 'Large Hadron Collider Analysis'
      parameters:
          - name: 'nevents'
            type: 'int'
            label: 'Number of Events'
            default: 100
      schema:
        source: 'from-github/phenochain'
        identifier: 'lhcoanalysis.yml'
    - identifier: 'madgraph_delphes'
      name: 'Madgraph Delphes'
      description: 'Generate collision events with MadGraph5_aMC@NLO and shower, hadronize, and simulate the response of a detector like CMS with Delphes and Pythia'
      parameters:
          - name: 'nevents'
            type: 'int'
            label: 'Number of Events'
            default: 100
      schema:
        source: 'from-github/phenochain'
        identifier: 'madgraph_delphes.yml'
    - identifier: 'madgraph_delphes_athena'
      name: 'Madgraph Delphes Athena'
      description: 'Madgraph Delphes Athena'
      parameters:
          - name: 'nevents'
            type: 'int'
            label: 'Number of Events'
            default: 100
      schema:
        source: 'from-github/phenochain'
        identifier: 'madgraph_delphes_athena.yml'
    - identifier: 'madgraph_rivet'
      name: 'Madgraph Rivet'
      description: 'Madgraph Rivet'
      parameters:
          - name: 'nevents'
            type: 'int'
            label: 'Number of Events'
            default: 100
      schema:
        source: 'from-github/phenochain'
        identifier: 'madgraph_rivet.yml'
    - identifier: 'parallel_md'
      name: 'Parallel Madgraph Delphes'
      description: 'Parallel Madgraph Delphes'
      parameters:
          - name: 'nevents'
            type: 'int'
            label: 'Number of Events'
            default: 100
      schema:
        source: 'from-github/phenochain'
        identifier: 'parallel_md.yml'
    - identifier: 'atlasexamples_fullchainderiv'
      name: 'Atlas Examples - Full chain deriv'
      description: 'Atlas Examples - Full chain deriv'
      schema:
        source: 'from-github/atlasexamples/fullchainderiv/'
        identifier: 'rootflow.yml'
    - identifier: 'atlasexamples_pileupfull'
      name: 'Atlas Examples - Pile-up full'
      description: 'Atlas Examples - Pile-up full'
      schema:
        source: 'from-github/atlasexamples/pileupfull'
        identifier: 'workflow.yml'
